'use strict';
const $=s=>document.querySelector(s), token=$('meta[name=archive-token]').content;
const statuses=['待投递','已投递','初筛','笔试','面试','Offer','已拒绝','已撤回'];
const fields=['company','title','url','jd','applied_date','status','notes'];
let apps=[],mails=[],selected=null,editing=null,mailSelected=null,nextPage='',view='applications',desktop=false;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const stamp=s=>s?new Date(s).toLocaleString('zh-CN'):'';
function toast(s){$('#toast').textContent=s;$('#toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').hidden=true,6500)}
async function api(path,data){const r=await fetch(path,{headers:{'X-Archive-Token':token,...(data===undefined?{}:{'Content-Type':'application/json'})},...(data===undefined?{}:{method:'POST',body:JSON.stringify(data)})});const p=await r.json();if(!r.ok)throw Error(p.error||'请求失败');return p}
function action(el,fn){el.addEventListener('click',async()=>{el.disabled=true;try{await fn()}catch(e){toast(e.message)}finally{el.disabled=false}})}
function badge(s){return `<span class="badge ${s==='Offer'?'good':s==='已拒绝'?'bad':''}">${esc(s)}</span>`}
async function reload(){apps=await api('/api/applications');renderStats();renderList();if(selected)await detail(selected)}
function renderStats(){const counts=[['全部机会',apps.length],['已投递',apps.filter(a=>a.status!=='待投递').length],['进行中',apps.filter(a=>['初筛','笔试','面试'].includes(a.status)).length],['收获 Offer',apps.filter(a=>a.status==='Offer').length]];$('#stats').innerHTML=counts.map(([s,n])=>`<div class="stat"><span>${s}</span><strong>${n}</strong></div>`).join('')}
function filtered(){const q=$('#search').value.trim().toLowerCase(),status=$('#status-filter').value,from=$('#date-from').value,to=$('#date-to').value,key=$('#sort').value;return apps.filter(a=>(!q||['company','title'].some(k=>a[k].toLowerCase().includes(q)))&&(!status||a.status===status)&&(!from||a.applied_date>=from)&&(!to||(a.applied_date&&a.applied_date<=to))).sort((a,b)=>key==='company'?a[key].localeCompare(b[key],'zh-CN'):b[key].localeCompare(a[key]))}
function renderList(){const rows=filtered();$('#list').innerHTML=rows.length?rows.map(a=>`<button class="record ${selected===a.id?'selected':''}" data-id="${a.id}"><div class="record-top"><strong>${esc(a.company)}</strong>${badge(a.status)}</div><p>${esc(a.title)}</p><small>${a.applied_date?'投递于 '+esc(a.applied_date):'尚未填写投递日期'}</small></button>`).join(''):`<div class="empty"><b>${apps.length?'没有匹配的投递':'从第一份投递开始'}</b>${apps.length?'试试调整搜索或筛选条件。':'点击右上角「新建投递」，保存网页与实际提交的材料。'}</div>`;$('#list').querySelectorAll('[data-id]').forEach(e=>e.onclick=()=>detail(e.dataset.id).catch(e=>toast(e.message)));if(!selected)$('#detail').innerHTML='<div class="empty"><b>你的求职时间线</b>选择一条投递，查看 JD、提交材料和状态历史。<br>所有文件都保留独立版本。</div>'}
async function detail(id){selected=id;const a=await api('/api/applications/'+id);renderList();$('#detail').innerHTML=`<div class="detail-head"><div><small>${esc(a.company)}</small><h2>${esc(a.title)}</h2>${badge(a.status)}</div><button id="edit-record">编辑 / 归档材料</button></div><div class="meta"><span>投递日期：${esc(a.applied_date||'未填写')}</span><span>更新：${stamp(a.updated_at)}</span></div>${a.url?`<a href="${esc(a.url)}" target="_blank" rel="noreferrer">打开投递网页 ↗</a>`:''}<h3>职位描述</h3><div class="prose">${esc(a.jd||'暂无 JD，可编辑或从网页抓取。')}</div>${a.notes?`<h3>备注</h3><div class="prose">${esc(a.notes)}</div>`:''}<h3>实际提交材料 · ${a.documents.length} 份</h3>${a.documents.map(d=>`<div class="file"><div><a href="/files/${d.id}">${esc(d.name)} ↓</a><small>${d.kind==='cv'?'CV':d.kind==='letter'?'动机信':'其他'} · ${esc(d.submitted_date||'未填日期')} · ${(d.size/1024).toFixed(1)} KB ${esc(d.label)}</small><small>归档：${stamp(d.created_at)}</small></div></div>`).join('')||'<p class="hint">尚未归档材料。编辑记录即可新增文件。</p>'}<h3>关联邮件 · ${a.mails.length} 封</h3>${a.mails.map(m=>`<button class="record" data-mail="${m.id}"><strong>${esc(m.subject)}</strong><small>${esc(m.sender)}</small></button>`).join('')||'<p class="hint">在求职邮箱中把邮件关联到这条投递。</p>'}<h3>更新历史</h3>${a.history.map(h=>`<details class="history"><summary>${stamp(h.created_at)} · ${esc(h.event)}</summary><pre class="prose">${esc(historyText(h.snapshot))}</pre></details>`).join('')}`;$('#edit-record').onclick=()=>openEditor(a);$('#detail').querySelectorAll('[data-mail]').forEach(e=>e.onclick=async()=>{showView('mail');await loadMails();showMail(e.dataset.mail)})}
function historyText(raw){try{const s=JSON.parse(raw);return `状态：${s.status}\n日期：${s.applied_date}\n公司：${s.company}\n职位：${s.title}\n网页：${s.url}\n备注：${s.notes}\n\nJD：\n${s.jd}`}catch{return raw}}
function openEditor(a=null){editing=a?.id||null;const f=$('#application-form');f.reset();for(const k of fields)f.elements[k].value=a?.[k]??(k==='status'?'已投递':k==='applied_date'?today():'');f.elements.submitted_date.value=a?.applied_date||today();$('#editor-title').textContent=a?'编辑投递 / 新增提交材料':'新建投递';$('#form-message').textContent='';$('#editor').showModal()}
async function file64(file){if(file.size>25*1024*1024)throw Error(file.name+' 超过 25 MB');return new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result.split(',')[1]);r.onerror=()=>reject(Error('文件读取失败'));r.readAsDataURL(file)})}
$('#application-form').onsubmit=async e=>{e.preventDefault();const save=$('#save');save.disabled=true;$('#form-message').textContent='正在归档，请稍候…';try{const f=e.target,p=Object.fromEntries(fields.map(k=>[k,f.elements[k].value]));p.new_letter=f.elements.new_letter.value;p.submitted_date=f.elements.submitted_date.value;p.document_label=f.elements.document_label.value;p.uploads=[];for(const [sel,kind] of [['#cv-files','cv'],['#letter-files','letter']])for(const file of $(sel).files)p.uploads.push({name:file.name,kind,data:await file64(file),submitted_date:f.elements.submitted_date.value,label:f.elements.document_label.value});if(p.uploads.length>10)throw Error('一次最多归档 10 个文件');const a=await api('/api/applications'+(editing?'/'+editing:''),p);selected=a.id;$('#editor').close();await reload();toast('已保存，新增材料已独立归档')}catch(e){$('#form-message').textContent=e.message}finally{save.disabled=false}};
action($('#fetch-jd'),async()=>{const f=$('#application-form');$('#form-message').textContent='正在读取公开网页…';try{const p=await api('/api/fetch-jd',{url:f.elements.url.value});f.elements.jd.value=p.jd;if(p.title)f.elements.title.value=p.title;if(p.company)f.elements.company.value=p.company;$('#form-message').textContent=p.warning||'已抓取，请核对职位描述后保存。'}catch(e){$('#form-message').textContent=e.message+'；可手动粘贴 JD。'}});
function showView(name){view=name;for(const n of ['applications','mail','settings'])$('#'+n+'-view').hidden=n!==name;document.querySelectorAll('nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===name));$('#page-title').textContent={applications:'投递档案',mail:'求职邮箱',settings:'备份与设置'}[name];$('#add').hidden=name!=='applications';$('#stats').hidden=name!=='applications';if(name==='mail'){gmailStatus().catch(e=>toast(e.message));loadMails().catch(e=>toast(e.message))}}
async function gmailStatus(){const s=await api('/api/gmail');$('#gmail-state').textContent=s.connected?`已连接 ${s.email} · 只读权限`:(s.configured?'配置已导入，点击连接 Gmail 完成授权。':'尚未连接。首次使用请先导入 Google 桌面 OAuth 配置。');$('#gmail-connect').disabled=!s.configured;$('#gmail-sync').disabled=!s.connected;return s}
$('#google-config').onchange=async e=>{try{const file=e.target.files[0];if(!file)return;if(file.size>100000)throw Error('配置文件过大');if(mails.length&&!confirm('导入新配置会清除当前邮件缓存，投递与材料保留。继续？'))return;await api('/api/gmail/configure',JSON.parse(await file.text()));await gmailStatus();await loadMails();toast('配置已导入，请连接 Gmail')}catch(e){toast(e.message)}finally{e.target.value=''}};
action($('#gmail-connect'),async()=>{const p=await api('/api/gmail/connect',{});const a=document.createElement('a');a.href=p.url;a.target='_blank';a.rel='noreferrer';a.click();toast('请在 Google 页面完成授权，然后刷新连接状态')});
action($('#gmail-status'),gmailStatus);
action($('#gmail-disconnect'),async()=>{if(!confirm('断开 Gmail 并删除本机已同步邮件？投递档案和附件保留。'))return;const r=await api('/api/gmail/disconnect',{});nextPage='';$('#gmail-more').disabled=true;await gmailStatus();await loadMails();toast(r.warning||'已断开并清除邮件缓存')});
async function sync(page=''){const r=await api('/api/gmail/sync',{query:$('#gmail-query').value,page_token:page});nextPage=r.next_page||'';$('#gmail-more').disabled=!nextPage;await loadMails();toast(`已同步 ${r.count} 封邮件${r.errors?.length?'，部分读取失败：'+r.errors.join('；'):''}`)}
action($('#gmail-sync'),()=>sync());$('#gmail-more').onclick=async()=>{const b=$('#gmail-more');b.disabled=true;try{await sync(nextPage)}catch(e){toast(e.message)}finally{b.disabled=!nextPage}};
async function loadMails(){mails=await api('/api/mails');renderMails();if(mailSelected&&mails.some(m=>m.id===mailSelected))showMail(mailSelected);else $('#mail-detail').innerHTML='<div class="empty"><b>邮件与投递放在一起</b>同步后选择邮件，查看正文、关联职位并手动更新状态。</div>'}
function renderMails(){const q=$('#mail-search').value.toLowerCase();const rows=mails.filter(m=>[m.sender,m.subject,m.body].some(s=>s.toLowerCase().includes(q)));$('#mail-list').innerHTML=rows.length?rows.map(m=>`<button class="record ${mailSelected===m.id?'selected':''}" data-id="${m.id}"><strong>${esc(m.subject||'（无主题）')}</strong><p>${esc(m.sender)}</p><small>${stamp(m.received_at)} ${m.application_id?'· 已关联':''}</small></button>`).join(''):'<div class="empty"><b>暂无邮件</b>连接 Gmail 并点击同步，或调整搜索条件。</div>';$('#mail-list').querySelectorAll('[data-id]').forEach(e=>e.onclick=()=>showMail(e.dataset.id))}
function suggestion(m){const s=(m.subject+' '+m.body).toLowerCase();if(/unfortunately|regret to|not selected|遗憾|拒绝|pas retenu/.test(s))return '已拒绝';if(/offer letter|offer of employment|录用通知|聘用|proposition d.embauche/.test(s))return 'Offer';if(/interview|面试|entretien/.test(s))return '面试';if(/assessment|笔试|coding test/.test(s))return '笔试';return ''}
function showMail(id){mailSelected=id;const m=mails.find(m=>m.id===id);if(!m)return;renderMails();const suggest=suggestion(m);$('#mail-detail').innerHTML=`<h2 class="mail-subject">${esc(m.subject||'（无主题）')}</h2><p class="hint">${esc(m.sender)}<br>${stamp(m.received_at)}</p><div class="link-controls"><select id="mail-app" aria-label="关联投递"><option value="">不关联</option>${apps.map(a=>`<option value="${a.id}" ${a.id===m.application_id?'selected':''}>${esc(a.company+' · '+a.title)}</option>`).join('')}</select><button id="link-mail">保存关联</button></div>${suggest?`<p class="hint">关键词建议：${badge(suggest)}。请核对正文，建议可能不准确。</p>`:''}<div class="link-controls"><select id="mail-status" aria-label="更新投递状态">${statuses.map(s=>`<option ${s===(suggest||'已投递')?'selected':''}>${esc(s)}</option>`).join('')}</select><button id="update-from-mail">确认更新关联职位状态</button></div><h3>邮件正文</h3><div class="prose">${esc(m.body||m.snippet||'暂无可读取的正文')}</div>`;action($('#link-mail'),async()=>{await api('/api/mails/link',{id:m.id,application_id:$('#mail-app').value});await loadMails();toast('邮件关联已保存')});action($('#update-from-mail'),async()=>{const aid=$('#mail-app').value;if(!aid)throw Error('请先选择关联职位');const status=$('#mail-status').value;if(!confirm('把所选投递更新为「'+status+'」？'))return;const a=await api('/api/applications/'+aid);a.status=status;await api('/api/applications/'+aid,Object.fromEntries(fields.map(k=>[k,a[k]])));await api('/api/mails/link',{id:m.id,application_id:aid});await reload();await loadMails();toast('投递状态已更新')})}
async function nativeExport(kind,id=''){if(!window.pywebview?.api?.export)throw Error('桌面窗口正在初始化，请稍后重试');const r=await window.pywebview.api.export(token,kind,id);if(r.error)throw Error(r.error);if(r.path)toast('已保存：'+r.path)}
async function download(path,name){if(desktop){await nativeExport(path==='/api/backup'?'backup':'csv');return}const r=await fetch(path,{headers:{'X-Archive-Token':token}});if(!r.ok)throw Error((await r.json()).error);const url=URL.createObjectURL(await r.blob()),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000)}
action($('#backup'),()=>download('/api/backup','职投档案_'+today()+'.zip'));action($('#csv'),()=>download('/api/csv','投递记录_'+today()+'.csv'));
$('#restore').onchange=async e=>{const file=e.target.files[0];try{if(!file)return;if(file.size>400*1024*1024)throw Error('备份上限 400 MB');if(!confirm('这会替换当前全部档案与材料。软件会先保存恢复前备份。确定恢复？'))return;toast('正在校验并恢复…');const r=await fetch('/api/restore',{method:'POST',headers:{'X-Archive-Token':token,'X-Confirm':'RESTORE','Content-Type':'application/zip'},body:file});const p=await r.json();if(!r.ok)throw Error(p.error);selected=null;mailSelected=null;await reload();await loadMails();toast('恢复完成；恢复前备份保存在本机 data/backups 文件夹')}catch(e){toast(e.message)}finally{e.target.value=''}};
action($('#shutdown'),async()=>{if(!confirm('停止本地服务？重新运行启动文件可以再次打开。'))return;await api('/api/shutdown',{});document.body.innerHTML='<main><h1>本地服务已停止</h1><p>你的档案已经保存在本机。重新运行「启动职投档案」即可继续。</p></main>'});
$('#add').onclick=()=>openEditor();$('#close-editor').onclick=()=>$('#editor').close();document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>showView(b.dataset.view));for(const s of statuses){$('#status-filter').add(new Option(s,s));$('#application-form').elements.status.add(new Option(s,s))}for(const id of ['search','status-filter','date-from','date-to','sort'])$('#'+id).addEventListener('input',renderList);$('#mail-search').oninput=renderMails;
document.addEventListener('click',e=>{const a=e.target.closest('a[href^="/files/"]');if(desktop&&a){e.preventDefault();nativeExport('document',a.getAttribute('href').split('/').pop()).catch(e=>toast(e.message))}});
async function boot(){try{await reload();const info=await api('/api/info');desktop=!!info.desktop;$('#data-path').textContent=info.data_dir;if(desktop){$('#shutdown').textContent='关闭应用';$('#eyebrow').textContent='你的本机求职工作台'}}catch(e){toast(e.message)}}boot();
